version: '3'

services:
  my-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: my-zookeeper
    container_name: my-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  my-kafka:
    image: confluentinc/cp-kafka:latest
    hostname: my-kafka
    container_name: my-kafka
    depends_on:
      - my-zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://my-kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - my-kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=test-event --partitions 3 --if-not-exists --bootstrap-server=my-kafka:9092"

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: my-control-center
    depends_on:
      - my-kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'my-kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
